name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - main

jobs:
  build-back:
    name: Build Back + Push Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 0-back

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check Gradlew Permissions
        run: ls -l gradlew && chmod +x gradlew

      - name: Build Application
        run: |
          ./gradlew build -x test -x check

      - name: Get Version
        id: get_version
        run: |
            VERSION=$(grep 'version =' build.gradle | sed -E "s/.*'([0-9]+\.[0-9]+\.[0-9]+)'.*/\1/")
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.CR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Docker Image (Back)
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/qpc-back:${{ env.VERSION }} .
          docker tag ghcr.io/${{ github.repository_owner }}/qpc-back:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/qpc-back:latest
          docker push ghcr.io/${{ github.repository_owner }}/qpc-back:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/qpc-back:latest
          
